---
title: "Demographic Analysis"
author: "Samantha Chiu & Leanna Moron"
date: "11/20/2020"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, loading FB data, include = FALSE}
library(foreign)
library(tidyverse)
library(haven)
library(knitr)
library(expss)
library(tinytex)
library(kableExtra)
library(dplyr)

week12 <- read_dta("C:/Users/Samantha/Desktop/week12.dta")
#View(week12)
data <- subset(week12, Q11 >= 2)
attach(data)

```

```{r, echo=FALSE, include=FALSE}
cro(Q9)
gender <- data$Q9
gender[gender == 3] <- NA
gender[gender == 4] <- NA
gender[gender == 5] <- NA
gender[gender == 6] <- NA

table_gender <- table(gender, data$Image)
prop.table(table_gender,2)
print(table_gender)
chisq.test((table_gender))
```
```{r, echo=FALSE, include=FALSE}
total.gender<-addmargins(table_gender)
total.gender[[length(total.gender)]]

totals <- addmargins(table(gender, Image))
totals
total <- c(333, 559, 61, 142, 198)
```

```{r, echo=FALSE, include=FALSE}
options(kableExtra.latex.load_packages = FALSE)
table <- rbind(formatC(prop.table(table_gender, 2)*100, format = "f", digits = 1), formatC(total, format ="d"))
rownames(table) <- c("Female", "Male", "Total N")
colnames(table) <- c("Neutral (%)", "COVID (%)", "Data Privacy (%)","Finance (%)", "Mental Health (%)")
table
```
```{r, echo = FALSE}
require(knitr)
kable(table, 
      caption = "Responses from five advertisement image samples by gender", 
      digits = 2, 
      align = "c") %>%
add_footnote ("X$^{2}$ = 72.4, 4 df, p < 0.001", notation = "none") %>%
row_spec(3, bold = TRUE) %>%
kable_styling (latex_options = c("striped", full_width = F, "hold_position"))
```



```{r, echo=FALSE, include=FALSE}
cro(Q10)
married <- data$Q10
married [married == 8] <-NA

table_married <- table(married, data$Image)
prop.table(table_married,2)
print(table_married)
chisq.test((table_married))
```
```{r, echo=FALSE, include=FALSE}
total.married<-addmargins(table_married)
total.married[[length(total.married)]]

totals <- addmargins(table(married, Image))
totals
total <- c(342, 568, 61, 146, 212)
```

```{r, echo=FALSE, include=FALSE}
options(kableExtra.latex.load_packages = FALSE)
table <- rbind(formatC(prop.table(table_married, 2)*100, format = "f", digits = 1), formatC(total, format ="d"))
rownames(table) <- c("Married", "Not Married", "Total N")
colnames(table) <- c("Neutral (%)", "COVID (%)", "Data Privacy (%)","Finance (%)", "Mental Health (%)")
table
```
```{r, kable table, echo = FALSE}
require(knitr)
kable(table, 
      caption = "Responses from five advertisement image samples by marital status", 
      digits = 2, 
      align = "c") %>%
add_footnote ("X$^{2}$ = 28.4, 4 df, p < 0.001", notation = "none") %>%
row_spec(3, bold = TRUE) %>%
kable_styling (latex_options = c("striped", full_width = F, "hold_position"))
```

```{r, echo=FALSE, include=FALSE}
cro(Q11)

age <-data$Q11
age[age == 2] <- 1
age[age == 3] <- 1
age[age == 4] <- 2
age[age == 5] <- 2
age[age == 6] <- 2
age[age == 7] <- 3

levels = c(1, 2, 3)
labels = c("19-35 years old", "36-65 years old", "66+ years old")

table_age <- table(age, data$Image)
prop.table(table_age,2)
print(table_age)
chisq.test((table_age))
```
```{r, echo=FALSE, include=FALSE}
total.age<-addmargins(table_age)
total.age[[length(total.age)]]

totals <- addmargins(table(age, Image))
totals
total <- c(343, 577, 61, 145, 214)
```

```{r, echo=FALSE, include=FALSE}
options(kableExtra.latex.load_packages = FALSE)
table <- rbind(formatC(prop.table(table_age, 2)*100, format = "f", digits = 1), formatC(total, format ="d"))
rownames(table) <- c("19-35 years old", "36-65 years old", "66+ years old", "Total N")
colnames(table) <- c("Neutral (%)", "COVID (%)", "Data Privacy (%)","Finance (%)", "Mental Health (%)")
table
```
```{r, echo = FALSE}
require(knitr)
kable(table, 
      caption = "Responses from five advertisement image samples by age group", 
      digits = 2, 
      align = "c") %>%
add_footnote ("X$^{2}$ = 187.39, 8 df, p < 0.001", notation = "none") %>%
row_spec(4, bold = TRUE) %>%
kable_styling (latex_options = c("striped", full_width = F, "hold_position"))
```

```{r, echo=FALSE, include=FALSE}
cro(Q12)
education <- data$Q12
summary(Q12)
education[education == 1] <- 1
education[education == 4] <- 1
education[education == 5] <- 2
education[education == 6] <- 3
education[education == 7] <- 3
levels = c(1,2,3)
labels = c("HS grad or less", "Some college", "BA or above")

cro(education)

table_education <- table(education, data$Image)
prop.table(table_education,2)
print(table_education)
chisq.test((table_education))
```

```{r, echo=FALSE, include=FALSE}
total.education<-addmargins(table_education)
total.education[[length(total.education)]]

totals <- addmargins(table(education, Image))
totals
total <- c(153, 300, 27, 82, 89)
```

```{r, echo=FALSE, include=FALSE}
options(kableExtra.latex.load_packages = FALSE)
table <- rbind(formatC(prop.table(table_education, 2)*100, format = "f", digits = 1), formatC(total, format ="d"))
rownames(table) <- c("HS grad or less", "Some college", "BA or above", "Total N")
colnames(table) <- c("Neutral (%)", "COVID (%)", "Data Privacy (%)","Finance (%)", "Mental Health (%)")
table
```

```{r, echo = FALSE}
require(knitr)
kable(table, 
      caption = "Responses from five advertisement image samples by education group", 
      digits = 2, 
      align = "c") %>%
add_footnote ("X$^{2}$ = 24.36, 8 df, p = 0.002", notation = "none") %>%
row_spec(4, bold = TRUE) %>%
kable_styling (latex_options = c("striped", full_width = F, "hold_position"))
```
```{r, echo=FALSE, include=FALSE}
library(haven)
uas244 <- read_dta("C:/Users/Samantha/Desktop/uas244.dta")
View(uas244)
attach(uas244)
```

```{r, include = FALSE}
colnames(uas244)
cro(uas244$gender)
cro(uas244$age)
cro(uas244$education)
```

